/*
 * Generated by ISE 20.11.10.5048 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F183_4718();
extern void F185_4880();
extern void F183_4722();
extern void F180_4551();
extern void F182_4715();
extern void F180_4556();
extern void F235_2552();
extern void F207_4397();
extern void F33_745();
extern EIF_REFERENCE F33_732();
extern EIF_BOOLEAN F33_744();
extern EIF_BOOLEAN F33_752();
extern void F33_754();
extern void F33_755();
extern void F33_756();
extern void F38_864();
extern EIF_TYPED_VALUE F38_865();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F183_4718;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F183_4722;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F180_4551;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F180_4556;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F235_2552;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F185_4880;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F182_4715;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F207_4397;
	egc_is_scoop_capable = 1;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F33_745;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F33_744;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F33_732;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F33_752;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F33_754;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F33_755;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F33_756;

	egc_str_dtype = 184;

	egc_immstr8_dtype = 183;

	egc_str32_dtype = 181;

	egc_immstr32_dtype = 180;
	egc_arr_dtype = 234;
	egc_tup_dtype = 133;
	egc_disp_rout_id = 1085;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x0122;
	egc_sp_wchar = 0xFD;
	egc_sp_bool = 0x02A3;
	egc_sp_uint8 = 0x01F4;
	egc_sp_uint16 = 0x014D;
	egc_sp_uint32 = 0x0305;
	egc_sp_uint64 = 0x022C;
	egc_sp_int8 = 0xFFFF;
	egc_sp_int16 = 0xFFFF;
	egc_sp_int32 = 0x0212;
	egc_sp_int64 = 0xFFFF;
	egc_sp_real32 = 0x01AC;
	egc_sp_real64 = 0x01D0;
	egc_sp_pointer = 0x0188;
	egc_sp_ref = 0xE6;

	egc_uint8_dtype = 153;
	egc_uint16_dtype = 150;
	egc_uint32_dtype = 147;
	egc_uint64_dtype = 171;
	egc_int8_dtype = 144;
	egc_int16_dtype = 141;
	egc_int32_dtype = 138;
	egc_int64_dtype = 135;
	egc_bool_dtype = 168;
	egc_real32_dtype = 156;
	egc_char_dtype = 165;
	egc_wchar_dtype = 162;
	egc_real64_dtype = 159;
	egc_point_dtype = 174;

	egc_exception_dtype = 50;
	egc_except_emnger_dtype = 32;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "jsonhandler";
	egc_system_location = "C:\\Users\\JOS\\Desktop\\LenguajesPRY3-EiffelJsonHandler-\\JSONHandler\\EIFGENs\\jsonhandler\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1611243683;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 781;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 1839;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 37;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F38_864;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F38_865;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 118; /* APPLICATION */
	}
}

#ifdef __cplusplus
}
#endif
