/*
 * Generated by ISE 20.11.10.5048 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F181_4622();
extern void F183_4784();
extern void F181_4626();
extern void F178_4455();
extern void F180_4619();
extern void F178_4460();
extern void F282_2456();
extern void F210_4301();
extern void F31_649();
extern EIF_REFERENCE F31_636();
extern EIF_BOOLEAN F31_648();
extern EIF_BOOLEAN F31_656();
extern void F31_658();
extern void F31_659();
extern void F31_660();
extern void F36_768();
extern EIF_TYPED_VALUE F36_769();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F181_4622;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F181_4626;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F178_4455;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F178_4460;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F282_2456;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F183_4784;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F180_4619;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F210_4301;
	egc_is_scoop_capable = 1;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F31_649;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F31_648;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F31_636;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F31_656;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F31_658;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F31_659;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F31_660;

	egc_str_dtype = 182;

	egc_immstr8_dtype = 181;

	egc_str32_dtype = 179;

	egc_immstr32_dtype = 178;
	egc_arr_dtype = 281;
	egc_tup_dtype = 131;
	egc_disp_rout_id = 992;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0xF5;
	egc_sp_wchar = 0x0275;
	egc_sp_bool = 0x01F1;
	egc_sp_uint8 = 0x01BA;
	egc_sp_uint16 = 0x029A;
	egc_sp_uint32 = 0x02E8;
	egc_sp_uint64 = 0x0210;
	egc_sp_int8 = 0xFFFF;
	egc_sp_int16 = 0xFFFF;
	egc_sp_int32 = 0x01D8;
	egc_sp_int64 = 0xFFFF;
	egc_sp_real32 = 0x0172;
	egc_sp_real64 = 0x0196;
	egc_sp_pointer = 0x014E;
	egc_sp_ref = 0x0115;

	egc_uint8_dtype = 151;
	egc_uint16_dtype = 148;
	egc_uint32_dtype = 145;
	egc_uint64_dtype = 169;
	egc_int8_dtype = 142;
	egc_int16_dtype = 139;
	egc_int32_dtype = 136;
	egc_int64_dtype = 133;
	egc_bool_dtype = 166;
	egc_real32_dtype = 154;
	egc_char_dtype = 163;
	egc_wchar_dtype = 160;
	egc_real64_dtype = 157;
	egc_point_dtype = 172;

	egc_exception_dtype = 48;
	egc_except_emnger_dtype = 30;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "jsonhandler";
	egc_system_location = "C:\\Users\\Personal\\Desktop\\LenguajesPRY3-EiffelJsonHandler-\\JSONHandler\\EIFGENs\\jsonhandler\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1609988845;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 779;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 1746;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 35;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F36_768;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F36_769;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 116; /* APPLICATION */
	}
}

#ifdef __cplusplus
}
#endif
